apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: powierzenia-postgresql-pvc
  name: powierzenia-postgresql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
status: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: powierzenia-postgresql
  labels:
    app: powierzenia-postgresql
type: Opaque
data:
  postgresql-password: M2YwZTJiN2RlZTRmNmNlMzlkMWVjZDhhNzIyY2I4NmIyZDdlZmEwZWJiYTkzYzJiYzFiMWU3MWI5ZTUy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: powierzenia-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powierzenia-postgresql
  template:
    metadata:
      labels:
        app: powierzenia-postgresql
    spec:
      volumes:
        - name: powierzenia-postgresql-pvc
          persistentVolumeClaim:
            claimName: powierzenia-postgresql-pvc
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: powierzenia
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: powierzenia-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: powierzenia-postgresql-pvc
              mountPath: /var/lib/postgresql/
          # resources:
          #   requests:
          #     memory: '256Mi'
          #     cpu: '400m'
          #   limits:
          #     memory: '500Mi'
          #     cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: powierzenia-postgresql
  namespace: default
spec:
  selector:
    app: powierzenia-postgresql
  ports:
    - port: 5432
