apiVersion: v1
kind: Service
metadata:
  name: powierzenia
  namespace: default
  labels:
    app: powierzenia
spec:
  selector:
    app: powierzenia
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
