apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: powierzenia-keycloak-claim0
  name: powierzenia-keycloak-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: powierzenia-keycloak
  name: powierzenia-keycloak
spec:
  selector:
    matchLabels:
      app: powierzenia-keycloak
      version: 'v1'
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: powierzenia-keycloak
    spec:
      volumes:
      - name: powierzenia-keycloak-claim0
        persistentVolumeClaim:
          claimName: powierzenia-keycloak-claim0
      containers:
      - args:
        - -b
        - 0.0.0.0
        - -Dkeycloak.migration.action=import
        - -Dkeycloak.migration.provider=dir
        - -Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config
        - -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
        - -Djboss.socket.binding.port-offset=1000
        - -Dkeycloak.profile.feature.upload_scripts=enabled
        env:
        - name: DB_VENDOR
          value: h2
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: KEYCLOAK_USER
          value: admin
        image: jboss/keycloak:8.0.1
        name: keycloak
        ports:
        - name: http
          containerPort: 9080
        - name: https
          containerPort: 9443
        - name: managment
          containerPort: 10990
        resources: {}
        volumeMounts:
        - mountPath: /opt/jboss/keycloak/realm-config
          name: powierzenia-keycloak-claim0
        # resources:
        #   requests:
        #     memory: '456Mi'
        #     cpu: '350m'
        #   limits:
        #     memory: '500Mi'
        #     cpu: '500m'
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 9080
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: powierzenia-keycloak
  name: powierzenia-keycloak
spec:
  ports:
  - name: http
    port: 9080
    targetPort: 9080
  - name: https
    port: 9443
    targetPort: 9443
  - name: managment
    port: 10990
    targetPort: 10990
  selector:
    app: powierzenia-keycloak
  type: LoadBalancer
